### ISSUE TITLE
Properties vs. kwargs

### ISSUE THREAD

**Issue by yoelk** [yoelk/instrumentino-v2#14]
In __init__ methods, should we use **kwargs for initializers or Kivy's properties.
Kivy treats all the properties of a class as possible initializers, so the effect would be the same.

One thing to consider is coding conventions and documentation.
Do we want our documentation to be like Kivy (based on properties) or to document possible kwargs.
The same goes for other class methods, though there I think kwargs and normal args are the only option anyway.

**Comment by snarfums** [comment]
How about: Since Kivy treats them all as "possible" initializers, maybe use **kwargs "everywhere" and then only specify/enforce/define them at the "physical device definition" classes?

Using the rationale for using Kivy properties from "the Kivy people": http://kivy.org/docs/api-kivy.properties.html) over **kwargs which are basically:

- "Value Checking / Validation": I can see these as definite plusses, especially since an Instrumentino "instrument" specification/definition for a physical component requires you to specify all sorts of properties that *should* be carefully defined and enforced (max/min pressure, voltages, etc.) by the user so if there's an easy way to map a "user specification for a device" 
to "Class specification for that device" it would probably be a good idea as the user specs. passed to the class will automatically be enforced.  For anything not related to hardware specifications/interfaces I'd say the properties may be unnecessary and may just get in the way.

In addition: When a user can directly input data into a component ("Set this to 1000"), if they go outside the allowed spec. of the physical device it would be easily caught.

The only hard part might be defining "how" to handle when things go outside of the enforced specification ("Error handling", below)

- "Observer Pattern": This could be beneficial, I just don't see how yet :)

- "Better Memory Management": ?

- and "Error Handling": This could be nice as for things that have properties and have "enforced input/output" as there are a few scenarios that could be nailed down as expected behaviour:
1. Instrument is running, component inputs/produces/reports a value outside of a valid range.  This produces an Error/Exception.  How is it handled?  I would assume you'd want the exception to stop/pause the instrument by default. But that could possibly be annoying (maybe at start up/power on something returns a 5000 or -1 for a second but normally it's not "valid". Or "valid" is supposed to be 1.000 to 2.000 but sometimes the thing reads 2.001. I don't know, just thinking of weird things hardware can do.)

2. A user inputs a value that's outside the valid range. I'd assume  by default you'd just want to pop up a warning and disallow the value.

Properties (all of them) appear to have 2 built in ways to handle errors (http://kivy.org/docs/api-kivy.properties.html#kivy.properties.OptionProperty): specify a specific value or a function.  I could see this as being useful at the hardware/interface/specification level to allow the user to explicitly determine what happens when a property throws an error if they need to override the two defaults mentioned above.

For documentation: I like the property level documentation look/feel, especially for things users will have to deal with a lot (Components, Instrument class, etc.), however possible kwargs might be nice for "everything" as it will all be done the same way and provide 'skeleton' documentation for everything that will be available in Eclipse. I guess it might boil down to who the documentation is for.  I can see someone trying to use/build an instrument using kivy-lke docs, but not wanting to wade through a lot of stuff just because it was documented internally (like Screens, the Chart, Menu, etc.).  Is there a way to auto-generate documentation for only some classes and make that "user API documentation"?

**Comment by yoelk** [comment]
Hi,
I also like the look&feel of kivy properties, so I started using them.
In __init__ methods, I don't treat kwargs because kivy does it for me via the class properties.
In other class methods I'm using kwargs or normal args.

About error handling for out-of-bounds values, I didn't know it can do it. might be a good idea to use this mechanism.
I'm currently working on setting up the components/variables class structure, so thanks for the tip. I'll look into it.
